name: Build and PR to develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean verify

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v6
        with:
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Merge ${{ github.ref_name }} into develop'
          body: 'Pull request automático via GitHub Actions'